apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
              name: kafka-in
            - containerPort: 9094
              name: kafka-out
          env:
            - name: KAFKA_BROKER_ID
              value: '1'
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: '1'
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: zookeeper-url
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: 'INTERNAL'
            - name: KAFKA_LISTENERS
              value: 'INTERNAL://:9092,OUTSIDE://:30094'
            - name: KAFKA_ADVERTISED_LISTENERS
              value: 'INTERNAL://kafka-service:9092,OUTSIDE://kubernetes.docker.internal:30094'
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: 'INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT'
