apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - name: kafka-in
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: kafka-out
      protocol: TCP
      port: 30094
      targetPort: 30094
      nodePort: 30094
